---

apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: debug-config
spec:
  args:
    - --debug

---

apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: crossplane-provider-helm
spec:
  credentials:
    source: InjectedIdentity

---

apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider
spec:
  credentials:
    source: InjectedIdentity
