---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-helm
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: kubernetes.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: crossplane-provider-kubernetes
spec:
  credentials:
    source: InjectedIdentity
