---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-helm
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: gravitee-api-management
spec:
  rollbackLimit: 2
  forProvider:
    chart:
      name: apim
      repository: https://helm.gravitee.io
      version: 4.4.9
    namespace: cto-development
  providerConfigRef:
    name: provider-helm
