---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: gravitee-api-management
spec:
  rollbackLimit: 2
  forProvider:
    chart:
      name: apim
      repository: https://helm.gravitee.io
      version: 4.4.9
    namespace: cto-development
    values:
      api:
        gateway:
          services:
            core:
              ingress:
                ingressClassName: "nginx"
                hosts: ["apim.127.0.0.1.nip.io"]
        ingress:
          management:
            ingressClassName: "nginx"
            hosts: ["apim.127.0.0.1.nip.io"]
        portal:
          ingressClassName: "nginx"
          hosts: ["apim.127.0.0.1.nip.io"]
      ui:
        ingress:
          ingressClassName: "nginx"
          hosts: ["apim.127.0.0.1.nip.io"]
      portal:
        ingress:
          ingressClassName: "nginx"
          hosts: ["apim.127.0.0.1.nip.io"]
  providerConfigRef:
    name: provider-helm
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: gravitee-access-management
spec:
  rollbackLimit: 2
  forProvider:
    chart:
      name: am
      repository: https://helm.gravitee.io
      version: 4.3.0
    namespace: cto-development
    values:
      api:
        ingress:
          ingressClassName: "nginx"
          hosts: ["am.127.0.0.1.nip.io"]
      gateway:
        ingress:
          ingressClassName: "nginx"
          hosts: ["am.127.0.0.1.nip.io"]
      services:
        ingress:
          ingressClassName: "nginx"
          hosts: ["am.127.0.0.1.nip.io"]
      ui:
        ingress:
          ingressClassName: "nginx"
          hosts: ["am.127.0.0.1.nip.io"]
  providerConfigRef:
    name: provider-helm
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: gravitee-alert-engine
spec:
  rollbackLimit: 2
  forProvider:
    chart:
      name: ae
      repository: https://helm.gravitee.io
      version: 1.1.46
    namespace: cto-development
    values:
      engine:
        ingress:
          ingressClassName: "nginx"
          hosts: ["ae.127.0.0.1.nip.io"]
  providerConfigRef:
    name: provider-helm
