---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: gravitee-api-management
spec:
  rollbackLimit: 2
  forProvider:
    chart:
      name: graviteeio-apimx3
      repository: https://helm.gravitee.io
      version: 4.6.0
    namespace: cto-development
  providerConfigRef:
    name: provider.pkg.crossplane.io/crossplane-provider-helm # crossplane-provider-helm
